spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingapi
    username: xenios
    password: xenios99251488
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

security:
  jwt:
    secret: "kztivzfn2xsCsQ0D-yfCqNIHTNvtHEcexKJSWoxcp2g="
