server:
  port: ${PORT:8080}
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingapi
    username: xenios
    password: xenios99251488
  jpa:
    hibernate:
      ddl-auto: update   # dev only
    show-sql: true
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

#Actuator - health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

security:
  jwt:
    secret: "kztivzfn2xsCsQ0D-yfCqNIHTNvtHEcexKJSWoxcp2g="